### ISSUE TITLE
直播延时严重

### ISSUE THREAD

**Issue by AmpletecGo** [zhw2590582/flv-player#14]
### Expected behaviour
正常播放直播
### Actual behaviour
直播延时严重，原因是 render 频率过慢
### Environment
电脑与手机
-   Browser:
-   Version:
-   Operating System:
-   Version:

**Comment by zhw2590582** [comment]
大概率是我的音视频同步没做好，你试试把音频禁用掉看看

**Comment by AmpletecGo** [comment]
这个问题在你还没加上音频就已经存在了，所以我猜应该跟音频没有关系

**Comment by zhw2590582** [comment]
有没有地址我这边可以访问到的？

**Comment by AmpletecGo** [comment]
给 http://domain/live/livestream.flv 可以吗？
http://cdn.vk7b0.cn/live/a123.flv

**Comment by zhw2590582** [comment]
访问不了，文件不存在

**Comment by emptycodes** [comment]
High latency of streaming is caused by default `videoChunk` value maybe. If you change tab in browser - latency is higher. FlvPlayer keeps frames in memory and will show it when you back to tab in speed close to framerate. When i set `videoChunk` to `5*1024`, player is showing all saved frames like a accelerated video and back to ~1s latency. Is it possible to add an option for start render from newest frame rather than old frames? 

P.S. It seems to me that when i change tab, browser's memory filling up by old frames and despite tab refresh data is still saved - close and create new tab helps.

Firefox 78.0.2, H264 High (no audio), Multiple decoder.
